# Generated by Django 5.1.2 on 2024-10-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(db_comment='Titulo del post', max_length=100)),
                ('post_content', models.TextField(db_comment='Contenido del post')),
                ('published_date', models.DateTimeField(auto_now=True, db_comment='Fecha de publicado el post')),
            ],
        ),
    ]
