# Generated by Django 5.1.2 on 2024-11-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
