# Generated by Django 5.1.2 on 2024-11-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='userdata'),
        ),
    ]
